spring.application.name=hotels
# Default profile
spring.profiles.active=h2

# Server configuration
server.port=8092

# Common Liquibase settings
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

